site_name: HP Christmas Light Show
site_description: Documentation about the Christmas Light Show
site_url: https://lightshow.thealmostengineer.com
copyright: Copyright 2020, Kenny Robinson

# repository information
repo_url: https://github.com/almostengr/lightshow
repo_name: Github
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 192.168.57.117:8080
  
extra_css: [css/extra.css]

# Appearance
theme:
  name: null
  custom_dir: 'readthedocs'
  highlightjs: false
  language: en
  static_templates:
    - 404.html
  include_search_page: true
  search_index_only: false
  highlightjs: false
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true

use_directory_urls: true
strict: false

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

extra:
  generator: false